### ISSUE TITLE
可以和ipv4版本的hosts合并使用么？

### ISSUE THREAD

**Issue by yichangshengwu** [googlehosts/hosts-ipv6#3]
ipv6 版本的 hosts 比 ipv4 版本的还是少呀，
如果想要吧两个 hosts 项目混合在一起用，可不可以呢？

如果可以的话，有什么工具可以方便地更新混合项目么，
就比如 “lhosts.sh”... 之类的？

**Comment by beyondgfw** [comment]
@yichangshengwu 计划ing 还未开始实现

**Comment by yichangshengwu** [comment]
计划中的只是工具吧？
那我手动把 ipv6 版本塞到 ipv4 版本 前面去，可不可以呢？

**Comment by SerCom-KC** [comment]
个人认为还需要进行域名去重，也就是同一个域名只能保留 IPv4 或 IPv6 中的一个，因为有些系统一旦设置 hosts 可能就会定死用两个中的一个了。
总之 hosts 文件里 IPv4 和 IPv6 条目共存是可以的。

**Comment by yichangshengwu** [comment]
反正闲着也是闲着，我就先试试吧，
看看能不能在 lhosts 的基础上塞点儿东西进去，不过这方面我连新手都算不上，不知道能不能碰到耗子2333
